# Generated by Django 3.0.6 on 2021-06-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('prname', models.CharField(max_length=100)),
                ('qty', models.IntegerField(max_length=11)),
                ('price', models.IntegerField(max_length=100)),
                ('pic', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('uname', models.CharField(max_length=30)),
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=35)),
                ('phno', models.IntegerField()),
                ('msg', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('uname', models.CharField(max_length=30)),
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=60)),
                ('pincode', models.IntegerField()),
                ('phno', models.IntegerField()),
                ('email', models.CharField(max_length=35)),
                ('pwd', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.IntegerField()),
                ('email', models.CharField(max_length=35)),
                ('phno', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('total', models.IntegerField()),
                ('addr', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvv_no', models.CharField(max_length=4)),
                ('card_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('exp_date', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prid', models.AutoField(primary_key=True, serialize=False)),
                ('prname', models.CharField(max_length=30)),
                ('descp', models.CharField(max_length=100)),
                ('pic', models.FileField(upload_to='media/')),
                ('catid', models.IntegerField(max_length=10)),
                ('qty', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
