# Generated by Django 3.0.6 on 2021-06-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='catid',
            field=models.IntegerField(),
        ),
    ]
