# Generated by Django 3.0.6 on 2021-06-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210618_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
