# Generated by Django 3.0.6 on 2021-06-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210618_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdb',
            name='cid',
        ),
        migrations.AddField(
            model_name='contactdb',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='addr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
