# Generated by Django 3.0.6 on 2021-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210618_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phno',
            new_name='billamt',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='pincode',
            new_name='custid',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='orderid',
            new_name='ordid',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total',
            new_name='prid1',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='uname',
            new_name='prid2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='state',
        ),
        migrations.AddField(
            model_name='orders',
            name='prid3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='qty1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='qty2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='qty3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='orders',
            table='ordertbl',
        ),
    ]
